import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

def markdown_to_docx(markdown_content, project_meta, output_path):
    doc = Document()
    
    # Cover page setup
    title = doc.add_heading('Functional Specification Document', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph()
    doc.add_paragraph()
    
    if project_meta:
        p_name = doc.add_heading(f"{project_meta.get('name', 'N/A')}", level=1)
        p_name.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph()
        p_ctx = doc.add_paragraph(f"Context: {project_meta.get('context', 'N/A')}")
        p_ctx.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
    doc.add_page_break()
    
    # Section content rendering
    for line in markdown_content.split('\n'):
        if line.startswith('# '):
            doc.add_heading(line[2:], level=1)
        elif line.startswith('## '):
            doc.add_heading(line[3:], level=2)
        elif line.startswith('### '):
            doc.add_heading(line[4:], level=3)
        elif line.startswith('- '):
            doc.add_paragraph(line[2:], style='List Bullet')
        elif line.strip():
            doc.add_paragraph(line)
            
    # Add footer functionality
    for section in doc.sections:
        footer = section.footer
        p = footer.paragraphs[0]
        p.text = "CONFIDENTIAL - Generated by SpecForge"
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.save(output_path)
    return output_path
